version: '3.2'
services:
  node:
    image: "node:14-alpine"
    container_name: "hw_node"
    user: "node"
    working_dir: /home/node/app
    # environment:
    #   - NODE_ENV=production
    volumes:
      - ./node:/home/node/app
    links:
      - db
    ports:
      - "80:3000"
    # command: ['sh', '-c', 'npm i']
    tty: true
    stdin_open: true
  db:
    image: "postgres:14-alpine"
    container_name: "hw_db"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: homework
    volumes:
      - postgres-vol:/var/lib/postgresql/data

volumes:
  postgres-vol:
